/* eslint-disable */
// tslint:disable
/**
 * ServiceApi 1-
 * 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import spouse from './api/spouse'
import * as t from './types'

export default function(app: Express, impl: t.ApiImplementation) {
	spouse(app, impl.spouse)
}
